# Instructivo de Acceso Eficiente a Datos Hidrológicos del IDEAM
### *Democratizando el conocimiento hidroclimático de Colombia a través de la ciencia de datos*

---

## 🌟 Bienvenidos
Este Notebook interactivo ha sido diseñado por el **Instituto de Hidrología, Meteorología y Estudios Ambientales (IDEAM)** para guiarlo paso a paso en la extracción, consulta y análisis de la información hidrológica oficial del país.

A través de este entorno, combinaremos el **lenguaje natural** (preguntas sencillas sobre qué datos necesita) con la potencia de **Python**, permitiendo que profesionales de la hidrología, investigadores, tomadores de decisión y ciudadanos accedan a las bases de datos institucionales de manera autónoma, ágil y directa.

---

## Relevancia Estratégica para el País
Colombia es un país de una riqueza hídrica excepcional, pero también altamente vulnerable a fenómenos de variabilidad climática como *El Niño* y *La Niña*, así como a eventos extremos de inundaciones y sequías.

Los datos de **niveles de ríos, caudales y transporte de sedimentos** recopilados por la red de estaciones del IDEAM son el corazón de la seguridad hidroclimática de la nación. Estos datos permiten:

1. **Gestión del Riesgo:** Monitorear alertas tempranas para proteger vidas ante crecientes súbitas.
2. **Planificación Ambiental:** Diseñar obras de infraestructura, acueductos y distritos de riego de manera sostenible.
3. **Soberanía Energética y Alimentaria:** Proveer insumos clave para la operación de hidroeléctricas y la planificación de los ciclos agrícolas del país.

---

## ⚡ Capacidades y Ventajas de esta Nueva Infraestructura
Para responder a los desafíos de la transformación digital, el IDEAM ha modernizado el acceso a sus series históricas y de tiempo real, disponiendo los datos en una infraestructura de almacenamiento de objetos de alta velocidad basada en **S3 (Simple Storage Service)**.

Al utilizar este Notebook para interactuar con dicha infraestructura, usted se beneficia de las siguientes ventajas:

* **Acceso "GIS-Free" y Descentralizado:** Ya no depende de software de escritorio pesado, consolas complejas o descargas manuales repetitivas en portales web. Todo el ciclo de consulta se verifique y resuelve desde este flujo de código.
* **Eficiencia Multiformato:** El sistema le permite elegir entre la descarga tradicional de archivos planos (`.csv`) para compatibilidad local, o la lectura ultra rápida de conjuntos de datos optimizados en formato **Parquet**, que reducen el tiempo de espera de minutos a solo segundos.
* **Consistencia e Integridad:** Al automatizar la consulta mediante Python, se eliminan los errores humanos en la manipulación manual de datos, garantizando que el análisis hidroclimático se realice siempre sobre la fuente oficial y actualizada del Instituto.

---

### 🛠️ ¿Cómo usar este instructivo?
El documento está estructurado de forma secuencial. Cada sección contiene una breve explicación teórica seguida de una celda de código.

1. **Lea la instrucción.**
2. **Configure los parámetros según su necesidad** (modificando los textos entre comillas).
3. **Ejecute la celda** (presionando `Shift + Enter` o haciendo clic en el botón de reproducción ▶️).

## PASO 0: Entendiendo las Vías de Acceso a los Datos S3 (Simple Storage Service)

Antes de realizar cualquier consulta, es fundamental comprender cómo están organizados los datos en la infraestructura del IDEAM y por qué la elección del formato transformará su experiencia de usuario.

El Instituto ha dispuesto la información hidrológica en un sistema de almacenamiento de objetos de alta velocidad llamado **S3 (Simple Storage Service)**. Como usuario, puede interactuar con este almacenamiento de dos formas distintas según su necesidad técnica y el volumen de datos que vaya a procesar.

A continuación, se explican las dos opciones disponibles para que elija la que mejor se adapte a su flujo de trabajo:

### 📑 Opción 1: Descarga de Archivos Temporales en Formato CSV
* **¿Cómo funciona?** El script se conecta al almacenamiento S3 (Simple Storage Service), busca el archivo de texto plano (`.csv`) correspondiente a su consulta, lo descarga completo a una ruta local o temporal de su máquina/servidor, y luego lo lee en memoria.
* **Ventajas:** Obtienes una copia física del archivo original estructurado por estaciones o variables, el cual puede guardar o abrir después en herramientas tradicionales si así lo requiere.
* **Desventajas:** Es la opción más lenta y pesada. Los archivos CSV no están indexados ni comprimidos eficientemente; descargar años de historia hidrológica de múltiples estaciones implicará transferir muchos Megabytes por la red, tardando más tiempo en procesar.
* **¿Cuándo usarla?:** Cuando necesite estrictamente el archivo plano original para auditoría o para guardarlo localmente en una ruta específica de su infraestructura.

### ⚡ Opción 2: Acceso Directo y Lectura Columnar en Formato Parquet
* **¿Cómo funciona?** El script no descarga archivos completos a su disco. Se conecta directamente a un set de datos optimizado en formato **Parquet** almacenado en el S3 (Simple Storage Service). Usando librerías especializadas en Python, lee "en la nube" únicamente las columnas y filas que coinciden con sus filtros (por ejemplo, solo la variable *Nivel* para un año específico).
* **Ventajas:** **Velocidad ultra rápida y máxima eficiencia.** Parquet es un formato de almacenamiento columnar y comprimido. Si un archivo contiene 20 variables pero solo pide *Nivel*, el sistema solo lee el fragmento del archivo que contiene los niveles. No hay descargas innecesarias de archivos gigantes, ahorrando red, memoria y tiempo de espera de minutos a solo fracciones de segundo.
* **Desventajas:** No genera un archivo de texto plano "legible a simple vista" en su disco local de manera inmediata; los datos van directo a la memoria del Notebook para su análisis.
* **¿Cuándo usarla?:** Siempre que sea posible. Es la opción recomendada para analítica de datos, creación de gráficos, modelos predictivos y consultas históricas masivas.

---

### 📊 Tabla Comparativa de Decisión

| Característica | Opción 1: CSV (.csv) | Opción 2: Parquet (.parquet) |
| :--- | :--- | :--- |
| **Ubicación del procesamiento** | Descarga local y luego procesa | Lectura directa en el almacenamiento S3 |
| **Velocidad de consulta** | 🐌 Más lenta (Depende del tamaño del archivo completo) | ⚡ Muy rápida (Solo lee lo que necesitas) |
| **Consumo de red / Ancho de banda** | Alto (Descarga todo el archivo) | Mínimo (Transfiere solo los datos filtrados) |
| **Uso ideal** | Respaldos físicos, uso en herramientas externas | Analítica en Python, reportes rápidos, series largas |

---
**Instrucciones:** En la siguiente celda de código (Paso 1), cambie el valor de la variable `metodo_acceso` escribiendo `"parquet"` o `"csv"` según su preferencia.

In [11]:
# ==============================================================================
# PASO 1: CONFIGURACIÓN DEL MÉTODO DE ACCESO
# ==============================================================================

# Instrucción: Escriba "parquet" para máxima velocidad o "csv" para descarga tradicional.
metodo_acceso = "csv"

# --- Lógica de validación (No modificar) ---
metodo_normalizado = metodo_acceso.strip().lower()

if metodo_normalizado in ["parquet", "csv"]:
    print(f"✅ Método configurado exitosamente: {metodo_normalizado.upper()}")
    if metodo_normalizado == "parquet":
        print("⚡ Estado: Lectura optimizada activada. No se descargarán archivos pesados.")
    else:
        print("📁 Estado: Descarga de archivos planos activada. Se requiere espacio en disco.")
else:
    print(f"❌ ERROR: '{metodo_acceso}' no es una opción válida.")
    print("Por favor, regrese a la variable 'metodo_acceso' y elija entre 'parquet' o 'csv'.")

✅ Método configurado exitosamente: CSV
📁 Estado: Descarga de archivos planos activada. Se requiere espacio en disco.

## PASO 2: Preparación del Entorno y Conexión a S3 (Simple Storage Service)

Para poder interactuar con el almacenamiento en la nube del IDEAM, necesitamos que este Notebook cuente con las librerías de Python adecuadas para la ciencia de datos y la lectura de sistemas de archivos remotos S3:

1. **`pandas`**: La librería estándar para la manipulación y análisis de estructuras de datos (DataFrames).
2. **`pyarrow`**: El motor encargado de procesar de forma ultra rápida el formato columnar Parquet.
3. **`s3fs`**: El conector que le permite a Python entender el almacenamiento de objetos S3 como si fuera un disco local.

En la siguiente celda de código, realizaremos la instalación silenciosa de estos componentes (en caso de que no estén instalados en su entorno) y definiremos las direcciones URL oficiales junto con los parámetros de acceso anónimo provistos por el servidor de S3 (Simple Storage Service) del IDEAM.

In [12]:
# ==============================================================================
# PASO 2: INSTALACIÓN DE LIBRERÍAS Y CONFIGURACIÓN DE RUTAS S3
# ==============================================================================

# 1. Instalación de dependencias requeridas en el entorno actual
print("⏳ Verificando e instalando librerías necesarias... Por favor espere.")
%pip install -q pandas pyarrow s3fs
print("✅ Librerías preparadas correctamente.")

# Importación de componentes base
import pandas as pd

# 2. Configuración de parámetros de conexión específicos para el S3 del IDEAM
opciones_almacenamiento = {
    "anon": True,                     # Acceso público institucional (sin credenciales)
    "client_kwargs": {
        "endpoint_url": "https://datos.ideam.gov.co/"  # Servidor host central de S3 IDEAM
    }
}

# 3. Definición del inventario de rutas S3 oficiales por componente y formato

# Catálogo de Variables Hidroclimáticas
url_parquet_variables = "s3://s3-estacionesideam/catalogo/variables/parquet/variables.parquet"
url_csv_variables = "s3://s3-estacionesideam/catalogo/variables/csv/variables.csv"

# Catálogo General de Estaciones del IDEAM
url_parquet_catalogo = "s3://s3-estacionesideam/catalogo/estaciones/parquet/catalogo.parquet"
url_csv_catalogo = "s3://s3-estacionesideam/catalogo/estaciones/csv/catalogo.csv"

# Series Históricas de Observaciones (Directorios raíz)
url_parquet_observaciones = "s3://s3-estacionesideam/observaciones/historicos/parquet"
url_csv_observaciones = "s3://s3-estacionesideam/observaciones/historicos/csv"

print("\n🌐 Infraestructura y catálogo de rutas S3 mapeados con éxito.")
print(f"📍 Endpoint Activo: {opciones_almacenamiento['client_kwargs']['endpoint_url']}")

⏳ Verificando e instalando librerías necesarias... Por favor espere.
/home/santy/Projects/GitProjects/Geopositioning-and-Navigation/.venv/bin/python: No module named pip
Note: you may need to restart the kernel to use updated packages.
✅ Librerías preparadas correctamente.

🌐 Infraestructura y catálogo de rutas S3 mapeados con éxito.
📍 Endpoint Activo: https://datos.ideam.gov.co/

## PASO 3: Exploración de Variables

En esta celda, seleccionaremos el parámetro hidrológico o meteorológico para que el sistema consulte en tiempo real el almacenamiento **S3 (Simple Storage Service)** y nos muestre el menú de opciones disponibles.

---
**Instrucciones:**  

1. En `grupo_parametro` escribiendo textualmente el nombre de la variable que desea explorar de acuerdo con el siguiente listado:

* CAUDAL
* CONCENTRACIÓN (CM)
* DIR VIENTO
* EVAPORACION
* HUM RELATIVA
* HUM SUELO
* NIVEL
* PRECIPITACION
* PRES ATMOS
* TEMP SUELO
* TEMPERATURA
* TRANSPORTE ( TM )
* VEL VIENTO


2. Ejecute la celda para listar las etiquetas disponibles, parámetro, periodo, unidad y descripción.

In [15]:
# ==============================================================================
# PASO 3: EXPLORACIÓN DEL CATÁLOGO DE VARIABLES EN S3
# ==============================================================================

# 1. Selección dinámica de la ruta y lectura del catálogo en S3 según el Paso 1
if metodo_normalizado == "parquet":
    df_variables = pd.read_parquet(url_parquet_variables, storage_options=opciones_almacenamiento)
else:
    df_variables = pd.read_csv(url_csv_variables, storage_options=opciones_almacenamiento)

# 2. Estandarización absoluta de la columna 'parametro' a Mayúscula Sostenida y sin espacios
df_variables['parametro'] = df_variables['parametro'].astype(str).str.strip().str.upper()

# ==============================================================================
# CONFIGURACIÓN: Defina el parámetro que desea explorar
# (El sistema es insensible a mayúsculas/minúsculas)
# ==============================================================================
grupo_parametro = "caudal"
# ==============================================================================

# Normalización de la entrada del usuario para la búsqueda
parametro_busqueda = grupo_parametro.strip().upper()

# 3. Filtrado de las opciones correspondientes en el catálogo
opciones_disponibles = df_variables[df_variables['parametro'] == parametro_busqueda]

# 4. Presentación de resultados unificados al usuario
if not opciones_disponibles.empty:
    print(f"📋 OPCIONES TÉCNICAS Y PERIODICIDADES DISPONIBLES PARA: '{parametro_busqueda}'")
    print("-" * 105)
    # Seleccionamos las columnas de interés institucional para el usuario temático
    columnas_vista = ['etiqueta', 'parametro', 'periodo', 'unidad', 'descripcion']
    print(opciones_disponibles[columnas_vista].to_string(index=False))
    print("-" * 105)
    print("\n💡 INSTRUCCIÓN para el siguiente paso:")
    print("Observe la columna 'etiqueta' en la tabla anterior, elija el código que necesita y continúe a la siguiente celda.")
else:
    print(f"❌ ERROR: '{grupo_parametro.upper()}' no se encuentra registrado en el catálogo del S3.")
    # Extraer el listado único y ordenado en mayúsculas para orientar al usuario en caso de error
    valores_validos = sorted(df_variables['parametro'].unique().tolist())
    print("\n💡 Parámetros válidos disponibles actualmente en el repositorio:")
    for v in valores_validos:
        print(f"  🔹 {v}")

📋 OPCIONES TÉCNICAS Y PERIODICIDADES DISPONIBLES PARA: 'CAUDAL'
---------------------------------------------------------------------------------------------------------
 etiqueta parametro periodo unidad           descripcion
   Q_MN_D    CAUDAL  Diario   m3/s  Caudal mínimo diario
   Q_MN_M    CAUDAL Mensual   m3/s Caudal mínimo mensual
Q_MEDIA_A    CAUDAL   Anual   m3/s    Caudal medio anual
Q_MEDIA_M    CAUDAL Mensual   m3/s  Caudal medio mensual
Q_MEDIA_D    CAUDAL  Diario   m3/s   Caudal medio diario
   Q_MN_A    CAUDAL   Anual   m3/s   Caudal mínimo anual
   Q_MX_D    CAUDAL  Diario   m3/s  Caudal máximo diario
   Q_MX_A    CAUDAL   Anual   m3/s   Caudal máximo anual
 CAUDAL_H    CAUDAL Horario   m3/s        Caudal horario
   Q_MX_M    CAUDAL Mensual   m3/s Caudal máximo mensual
---------------------------------------------------------------------------------------------------------

💡 INSTRUCCIÓN para el siguiente paso:
Observe la columna 'etiqueta' en la tabla anterior, elija el código que necesita y continúe a la siguiente celda.

## PASO 4: Selección y Activación de la Etiqueta de Estudio

Una misma variable hidrológica puede ser medida en diferentes intervalos de tiempo (horario, diario, mensual, anual). En la infraestructura del IDEAM, cada una de estas combinaciones posee un código técnico único llamado **Etiqueta**.

Con la tabla del paso anterior en pantalla, usted ya conoce los códigos técnicos (`etiqueta`) que maneja el IDEAM para cada periodicidad.

En esta celda, ingresará la etiqueta específica que desea consultar. El sistema validará que el código ingresado exista en el repositorio S3 y extraerá de forma automática los metadatos de control para asegurar la consistencia de los datos en el resto del proceso.

---
**Instrucciones:** Modifique el valor de la variable `etiqueta_seleccionada` copiando y pegando textualmente el código de la columna `etiqueta` de la tabla anterior (por ejemplo: `"0248"`, `"TR_QS_M"`). Luego, ejecute la celda.

In [33]:
# ==============================================================================
# PASO 4: CONFIGURACIÓN Y VALIDACIÓN DE LA ETIQUETA ACTIVA
# ==============================================================================

# ==============================================================================
# MODIFIQUE AQUÍ: Copie y pegue la ETIQUETA exacta que desea estudiar
# ==============================================================================
etiqueta_seleccionada = "Q_MEDIA_A"
# ==============================================================================

# --- Lógica de Validación Institucional (No modificar) ---

# Aseguramos que el catálogo esté cargado en memoria desde el paso anterior
if 'df_variables' in locals():
    # Limpieza de espacios de la entrada del usuario
    etiqueta_usuario = etiqueta_seleccionada.strip()

    # Búsqueda estricta de la etiqueta en el catálogo de variables
    registro_activo = df_variables[df_variables['etiqueta'] == etiqueta_usuario]

    if not registro_activo.empty and etiqueta_usuario != "Cambie_Aqui_Por_La_Etiqueta":
        variable_confirmada = registro_activo.iloc[0]

        # Declaración de variables globales de control para el resto del Notebook
        ETIQUETA_ESTUDIO = variable_confirmada['etiqueta']
        NOMBRE_ESTUDIO = variable_confirmada['parametro']
        PERIODICIDAD_ESTUDIO = variable_confirmada['periodo']
        UNIDAD_ESTUDIO = variable_confirmada['unidad']
        DESCRIPCION_ESTUDIO = variable_confirmada['descripcion']

        print(f"🎯 ¡ETIQUETA DE ESTUDIO ACTIVADA DE FORMA EXITOSA!")
        print("-" * 60)
        print(f"🔹 Código Técnico: '{ETIQUETA_ESTUDIO}'")
        print(f"🔹 Variable Base:   {NOMBRE_ESTUDIO}")
        print(f"🔹 Periodicidad:    {PERIODICIDAD_ESTUDIO}")
        print(f"🔹 Unidad de Medida: {UNIDAD_ESTUDIO}")
        print(f"🔹 Detalle Oficial: {DESCRIPCION_ESTUDIO}")
        print("-" * 60)
        print("\n🚀 El entorno está listo. Proceda al siguiente paso para configurar las estaciones.")

    else:
        if etiqueta_usuario == etiqueta_seleccionada:#"Cambie_Aqui_Por_La_Etiqueta":
            print("💡 INSTRUCCIÓN: Por favor, reemplace el texto 'Cambie_Aqui_Por_La_Etiqueta' por un código válido")
            print("de la columna 'etiqueta' de la tabla anterior y vuelva a ejecutar esta celda.")
        else:
            print(f"❌ ERROR: La etiqueta '{etiqueta_seleccionada}' no se encuentra registrada en el catálogo.")
            print("Por favor, revise la tabla del Paso 3 y copie el código de forma exacta.")
else:
    print("❌ ERROR DE SECUENCIA: No se encuentra el catálogo de variables en memoria.")
    print("Por favor, asegúrese de haber ejecutado primero la celda del Paso 3.")

🎯 ¡ETIQUETA DE ESTUDIO ACTIVADA DE FORMA EXITOSA!
------------------------------------------------------------
🔹 Código Técnico: 'Q_MEDIA_A'
🔹 Variable Base:   CAUDAL
🔹 Periodicidad:    Anual
🔹 Unidad de Medida: m3/s
🔹 Detalle Oficial: Caudal medio anual
------------------------------------------------------------

🚀 El entorno está listo. Proceda al siguiente paso para configurar las estaciones.

## PASO 5A: Selección del Criterio Geográfico de Consulta

El catálogo de estaciones del IDEAM cuenta con diferentes agregaciones políticas e hidrográficas. En este paso, usted debe elegir bajo cuál de estos criterios desea delimitar su consulta.

---
**Instrucciones:** Modifique la variable `criterio_elegido` escribiendo textualmente el nombre de la columna por la cual desea filtrar, seleccionando una de las siguientes opciones:
* `"Departamento"` (División político-administrativa principal)
* `"Municipio"` (Municipios de Colombia)
* `"Area_Hidrografica"` (Macrocuencas institucionales)
* `"Zona_Hidrografica"` (Cuencas principales)
* `"Subzona_Hidrografica"` (Subcuencas o ríos específicos)
* `"Corriente"` (Nombre del cuerpo de agua / río / quebrada)
* `"Area_Operativa"` (Zonificación de control interno del IDEAM)

In [34]:
# ==============================================================================
# PASO 5A: SELECCIÓN Y CONFIGURACIÓN DEL CRITERIO GEOGRÁFICO
# ==============================================================================

# ==============================================================================
# CONFIGURACIÓN: Defina la dimensión espacial por la cual desea filtrar
# ==============================================================================
criterio_elegido = "Subzona_Hidrografica"
# ==============================================================================

# 1. Selección dinámica y lectura del catálogo general de estaciones en S3
if metodo_normalizado == "parquet":
    df_estaciones = pd.read_parquet(url_parquet_catalogo, storage_options=opciones_almacenamiento)
else:
    df_estaciones = pd.read_csv(url_csv_catalogo, storage_options=opciones_almacenamiento)

# Lista oficial de columnas espaciales válidas en el catálogo del IDEAM
criterios_validos = [
    "Departamento", "Municipio", "Area_Hidrografica",
    "Zona_Hidrografica", "Subzona_Hidrografica", "Corriente", "Area_Operativa"
]

# FILTRADO INSTITUCIONAL: Solo red propia del IDEAM
# Definimos la entidad objetivo según los datos oficiales
entidad_objetivo = 'INSTITUTO DE HIDROLOGÍA METEOROLOGÍA Y ESTUDIOS AMBIENTALES'

if 'Entidad' in df_estaciones.columns:
    # Filtramos el DataFrame para conservar solo las estaciones de la red propia
    df_estaciones = df_estaciones[df_estaciones['Entidad'].str.upper() == entidad_objetivo].copy()
    print(f"✅ Filtro aplicado: Trabajando exclusivamente con {len(df_estaciones)} estaciones de la red propia IDEAM.")
else:
    print("⚠️ ADVERTENCIA: La columna 'Entidad' no existe en el catálogo, no se pudo filtrar por red propia.")

# Normalización preventiva de la entrada del usuario
CRITERIO_GEOGRAFICO_ACTIVO = criterio_elegido.strip()

# Validación de consistencia de la columna
# Buscamos coincidencia exacta ignorando mayúsculas/minúsculas
coincidencia_criterio = next((c for c in criterios_validos if c.lower() == CRITERIO_GEOGRAFICO_ACTIVO.lower()), None)

if coincidencia_criterio:
    CRITERIO_GEOGRAFICO_ACTIVO = coincidencia_criterio
    print(f"✅ CRITERIO GEOGRÁFICO FIJADO CON ÉXITO")
    print("-" * 60)
    print(f"📍 Criterio seleccionado: '{CRITERIO_GEOGRAFICO_ACTIVO}'")
    print("-" * 60)
    print("\n🚀 Criterio configurado en memoria. Continúe a la siguiente celda para explorar los valores reales disponibles.")
else:
    print(f"❌ ERROR: '{criterio_elegido}' no es un criterio geográfico válido.")
    print("\n💡 Por favor, elija y escriba exactamente una de las siguientes opciones:")
    for opcion in criterios_validos:
        print(f"  🔹 {opcion}")

✅ Filtro aplicado: Trabajando exclusivamente con 4522 estaciones de la red propia IDEAM.
✅ CRITERIO GEOGRÁFICO FIJADO CON ÉXITO
------------------------------------------------------------
📍 Criterio seleccionado: 'Subzona_Hidrografica'
------------------------------------------------------------

🚀 Criterio configurado en memoria. Continúe a la siguiente celda para explorar los valores reales disponibles.

## PASO 5B: Listado de valores por consulta geográfica en el Servidor S3

Una vez definido el criterio en el paso anterior, el sistema se conectará en tiempo real a la infraestructura **S3 (Simple Storage Service)** del IDEAM para extraer e imprimir el listado único y ordenado de registros.

In [35]:
# ==============================================================================
# PASO 5B: LECTURA Y PRESENTACIÓN DE VALORES VÁLIDOS DESDE EL S3
# ==============================================================================

# 1. Selección dinámica y lectura del catálogo general de estaciones en S3
if metodo_normalizado == "parquet":
    df_estaciones = pd.read_parquet(url_parquet_catalogo, storage_options=opciones_almacenamiento)
else:
    df_estaciones = pd.read_csv(url_csv_catalogo, storage_options=opciones_almacenamiento)

# Aseguramos que el Índice 'Codigo' pase a ser una columna para su extracción
if df_estaciones.index.name == 'Codigo' or 'Codigo' not in df_estaciones.columns:
    df_estaciones = df_estaciones.reset_index()

# FILTRADO INSTITUCIONAL: Solo red propia del IDEAM
# Definimos la entidad objetivo según los datos oficiales
entidad_objetivo = 'INSTITUTO DE HIDROLOGÍA METEOROLOGÍA Y ESTUDIOS AMBIENTALES'

if 'Entidad' in df_estaciones.columns:
    # Filtramos el DataFrame para conservar solo las estaciones de la red propia
    df_estaciones = df_estaciones[df_estaciones['Entidad'].str.upper() == entidad_objetivo].copy()
    print(f"✅ Filtro aplicado: Trabajando exclusivamente con {len(df_estaciones)} estaciones de la red propia IDEAM.")
else:
    print("⚠️ ADVERTENCIA: La columna 'Entidad' no existe en el catálogo, no se pudo filtrar por red propia.")

# 2. Extracción de valores reales únicos basados en el criterio del Paso 5A
if 'CRITERIO_GEOGRAFICO_ACTIVO' in locals() and CRITERIO_GEOGRAFICO_ACTIVO in df_estaciones.columns:

    # Estandarizamos los valores a mayúsculas sostenidas y removemos espacios en blanco ocultos
    valores_reales = df_estaciones[CRITERIO_GEOGRAFICO_ACTIVO].dropna().astype(str).str.strip().str.upper()
    lista_valores_unicos = sorted(valores_reales.unique().tolist())

    print(f"📋 VALORES VÁLIDOS DISPONIBLES EN EL S3 PARA: '{CRITERIO_GEOGRAFICO_ACTIVO.upper()}'")
    print("-" * 90)
    for i, valor in enumerate(lista_valores_unicos, start=1):
        print(f" 🔹 {valor}")
    print("-" * 90)
    print(f"\n💡 TOTAL DE OPCIONES ENCONTRADAS: {len(lista_valores_unicos)}")
    print("📌 INSTRUCCIÓN: Copie textualmente uno de los nombres en mayúscula, páselo a la siguiente celda y ejecútela.")
else:
    print("❌ ERROR DE SECUENCIA: No se encuentra configurado el criterio geográfico activo.")
    print("Por favor, asegúrese de haber ejecutado con éxito la celda del Paso 5A.")

✅ Filtro aplicado: Trabajando exclusivamente con 4522 estaciones de la red propia IDEAM.
📋 VALORES VÁLIDOS DISPONIBLES EN EL S3 PARA: 'SUBZONA_HIDROGRAFICA'
------------------------------------------------------------------------------------------
 🔹 ALTO ATRATO
 🔹 ALTO CAQUETA
 🔹 ALTO CESAR
 🔹 ALTO GUAVIARE
 🔹 ALTO MAGDALENA
 🔹 ALTO NECHÍ
 🔹 ALTO RÍO CAUCA
 🔹 ALTO RÍO PUTUMAYO
 🔹 ALTO RÍO TOMO
 🔹 ALTO SALDAÑA
 🔹 ALTO SAN JORGE
 🔹 ALTO SINÚ - URRÁ
 🔹 ARROYOS DIRECTOS AL CARIBE
 🔹 BAJO CATATUMBO
 🔹 BAJO CESAR
 🔹 BAJO GUAVIARE
 🔹 BAJO NECHÍ (MD)
 🔹 BAJO RÍO APAPORIS
 🔹 BAJO RÍO TOMO
 🔹 BAJO SALDAÑA
 🔹 BAJO SAN JORGE - LA MOJANA
 🔹 BAJO SINÚ
 🔹 BAJO VAUPÉS
 🔹 BAJO VICHADA
 🔹 CANAL DEL DIQUE MARGEN DERECHO
 🔹 CANAL DEL DIQUE MARGEN IZQUIERDA
 🔹 CAÑO GUANÁPALO Y OTROS DIRECTOS AL META
 🔹 CAÑO LIONI O TERECAY
 🔹 CAÑO MATAVÉN
 🔹 CGA GRANDE DE SANTA MARTA
 🔹 DAGUA - BUENAVENTURA - BAHIA MÁLAGA
 🔹 DIRECTOS AL BAJO MAGDALENA ENTRE CALAMAR Y DESEMBOCADURA
 🔹 DIRECTOS AL BAJO MAGDALENA ENTRE EL PLATO Y CALAMAR
 🔹 DIRECTOS AL BAJO NECHÍ (MI)
 🔹 DIRECTOS AL CAUCA ENTRE PTO VALDIVIA Y RÍO NECHÍ
 🔹 DIRECTOS AL MAGDALENA (BRAZO MORALES)
 🔹 DIRECTOS AL MAGDALENA ENTRE RÍOS SECO Y NEGRO (MD)
 🔹 DIRECTOS AL MAGDALENA MEDIO ENTRE RÍOS NEGRO
 🔹 DIRECTOS AL META ENTRE RÍOS CUSIANA Y CRAVO SUR
 🔹 DIRECTOS AL RÍO META ENTRE RÍOS CUSIANA Y CARARE
 🔹 DIRECTOS AL RÍO META ENTRE RÍOS HUMEA Y UPIA (MI)
 🔹 DIRECTOS AL RÍO META ENTRE RÍOS PAUTO Y CARARE
 🔹 DIRECTOS ATRATO ENTRE RÍOS BEBARAMÁ Y MURRÍ (MD)
 🔹 DIRECTOS ATRATO ENTRE RÍOS QUITO Y BOJAYÁ (MI)
 🔹 DIRECTOS BAJO ATRATO ENTRE RÍO SUCIO Y DESEMBOCADURA
 🔹 DIRECTOS BAJO CAUCA - CGA LA RAYA ENTRE RÍO NECHÍ
 🔹 DIRECTOS BAJO MAGDALENA ENTRE EL BANCO Y EL PLATO
 🔹 DIRECTOS BAJO META ENTRE RÍOS CASANARE Y ORINOCO
 🔹 DIRECTOS CARIBE - AY.SHARIMAHANA ALTA GUAJIRA
 🔹 DIRECTOS CARIBE GOLFO DE MORROSQUILLO
 🔹 DIRECTOS MAGDALENA ENTRE RÍOS CABRERA Y SUMAPAZ
 🔹 DIRECTOS MAGDALENA ENTRE RÍOS GUARINÓ Y LA MIEL
 🔹 DIRECTOS MAGDALENA MEDIO ENTRE RÍOS LA MIEL Y NARE
 🔹 DIRECTOS ORINOCO ENTRE RÍOS TOMO Y META (MI)
 🔹 DIRECTOS PACIFICO FRONTERA PANAMÁ
 🔹 DIRECTOS RIO METICA ENTRE RÍOS GUAYURIBA Y YUCAO
 🔹 DIRECTOS RÍO AMAZONAS (MI)
 🔹 DIRECTOS RÍO ARAUCA (MD)
 🔹 DIRECTOS RÍO CAUCA  ENTRE RÍO SAN JUAN Y  PTO VALDIVIA
 🔹 DIRECTOS RÍO CAUCA ENTRE RÍO SAN JUAN Y PTO VALDIA
 🔹 JUNCAL Y OTROS RIOS DIRECTOS AL MAGDALENA
 🔹 LAGO DE TOTA
 🔹 MEDIO CESAR
 🔹 MEDIO GUAVIARE
 🔹 MEDIO SALDAÑA
 🔹 MEDIO SINÚ
 🔹 OTRAS ISLAS DEL CARIBE Y ZONA MARITIMA
 🔹 PROVIDENCIA
 🔹 QUEBRADA EL CARMEN Y OTROS DIRECTOS AL MAGDALENA
 🔹 R._INÍRIDA_(MI),_HASTA_BOCAS_CAÑO_BOCÓN,_Y_R._LAS VIÑAS
 🔹 RIO BANADIA Y OTROS DIRECTOS AL RÍO ARAUCA
 🔹 RIO CANALETE Y OTROS ARROYOS DIRECTOS AL CARIBE
 🔹 RIO FORTALECILLAS Y OTROS
 🔹 RIO GUACHACA - MENDIGUACA Y BURITACA
 🔹 RIO METICA (GUAMAL - HUMADEA)
 🔹 RIO NEIVA
 🔹 RIO SALADO Y OTROS DIRECTOS CAUCA
 🔹 RIO TAPIAS Y OTROS DIRECTOS AL CAUCA
 🔹 RIOS ARROYOHONDO - YUMBO - MULALO - VIJES - YOTOCO
 🔹 RIOS LAS CAÑAS - LOS MICOS Y OBANDO
 🔹 RIOS PESCADOR - RUT - CHANCO - CATARINA Y CAÑAVERAL
 🔹 RIÓ SAN BARTOLO Y OTROS DIRECTOS AL MAGDALENA MEDIO
 🔹 RÍO  PIEDRAS - RÍO MANZANARES
 🔹 RÍO AIPE, RÍO CHENCHE Y OTROS DIRECTOS AL MAGDALENA
 🔹 RÍO ALGODONAL (ALTO CATATUMBO)
 🔹 RÍO AMOYÁ
 🔹 RÍO ANCHICAYÁ
 🔹 RÍO ANCHO Y OTROS DIRECTOS AL CARIBE
 🔹 RÍO ANDÁGUEDA
 🔹 RÍO ARIARI
 🔹 RÍO ARIGUANÍ
 🔹 RÍO ARIPORO
 🔹 RÍO ARMA
 🔹 RÍO ATÁ
 🔹 RÍO BACHÉ
 🔹 RÍO BAUDÓ
 🔹 RÍO BEBARAMÁ Y OTROS DIRECTOS ATRATO (MD)
 🔹 RÍO BOGOTÁ
 🔹 RÍO BOJABÁ
 🔹 RÍO BOJAYÁ
 🔹 RÍO BUGALAGRANDE
 🔹 RÍO CABI Y OTROS DIRECTOS ATRATO (MD)
 🔹 RÍO CABRERA
 🔹 RÍO CAGUAN ALTO
 🔹 RÍO CAGUAN BAJO
 🔹 RÍO CAJÓN
 🔹 RÍO CAMARONES Y OTROS DIRECTOS CARIBE
 🔹 RÍO CAPOMA Y OTROS DIRECTOS AL SAN JUAN
 🔹 RÍO CAQUETA BAJO
 🔹 RÍO CAQUETA MEDIO
 🔹 RÍO CARARE (MINERO)
 🔹 RÍO CARRAIPIA - PARAGUACHON, DIRECTOS AL GOLFO MARACAIBO
 🔹 RÍO CARÁ-PARANÁ
 🔹 RÍO CASANARE
 🔹 RÍO CHICAMOCHA
 🔹 RÍO CHINCHINÁ
 🔹 RÍO CHÍTAGA
 🔹 RÍO CIMITARRA Y OTROS DIRECTOS AL MAGDALENA
 🔹 RÍO COBUGÓN - RÍO COBARÍA
 🔹 RÍO COELLO
 🔹 RÍO COTUHE
 🔹 RÍO CRAVO NORTE
 🔹 RÍO CRAVO SUR
 🔹 RÍO CUSIANA
 🔹 RÍO DEL SUROESTE Y DIRECTOS RÍO DE ORO
 🔹 RÍO DESBARATADO
 🔹 RÍO DOCAMPADÓ Y DIRECTOS PACÍFICO
 🔹 RÍO DON DIEGO
 🔹 RÍO FONCE
 🔹 RÍO FRÍO
 🔹 RÍO FRÍO Y OTROS DIRECTOS AL CAUCA
 🔹 RÍO GARAGOA
 🔹 RÍO GUACAVÍA
 🔹 RÍO GUACHAL (BOLO - FRAILE Y PÁRRAGA)
 🔹 RÍO GUALÍ
 🔹 RÍO GUAPE
 🔹 RÍO GUAPI
 🔹 RÍO GUARINÓ
 🔹 RÍO GUATIQUÍA
 🔹 RÍO GUAVIO
 🔹 RÍO GUAYABERO
 🔹 RÍO GUAYAS
 🔹 RÍO GUAYURIBA
 🔹 RÍO GUEJAR
 🔹 RÍO GUÁITARA
 🔹 RÍO HUMEA
 🔹 RÍO IGARÁ-PARANÁ
 🔹 RÍO INÍRIDA ALTO
 🔹 RÍO JUANANBÚ
 🔹 RÍO LA MIEL (SAMANÁ)
 🔹 RÍO LA VIEJA
 🔹 RÍO LAGUNILLA Y OTROS DIRECTOS AL MAGDALENA
 🔹 RÍO LEBRIJA Y OTROS DIRECTOS AL MAGDALENA
 🔹 RÍO LENGUPÁ
 🔹 RÍO LEÓN
 🔹 RÍO LUISA Y OTROS DIRECTOS AL MAGDALENA
 🔹 RÍO MANACACIAS
 🔹 RÍO MARGUA
 🔹 RÍO MAYO
 🔹 RÍO MELÚA
 🔹 RÍO MESAY
 🔹 RÍO MIRA
 🔹 RÍO MUCO
 🔹 RÍO MULATOS Y OTROS DIRECTOS AL CARIBE
 🔹 RÍO MURINDÓ - DIRECTOS AL ATRATO
 🔹 RÍO MURRÍ
 🔹 RÍO NAPIPÍ - RÍO OPOGADÓ
 🔹 RÍO NARE
 🔹 RÍO NAYA - YURUMANGUÍ
 🔹 RÍO NEGRO
 🔹 RÍO NUEVO PRESIDENTE - TRES BOCAS (SARDINATA, TIBU)
 🔹 RÍO OPÍA
 🔹 RÍO OPÓN
 🔹 RÍO ORTEGUAZA
 🔹 RÍO OTÚN Y OTROS DIRECTOS AL CAUCA
 🔹 RÍO OVEJAS
 🔹 RÍO PAILA
 🔹 RÍO PALACÉ
 🔹 RÍO PALO
 🔹 RÍO PAMPLONITA
 🔹 RÍO PATIA ALTO
 🔹 RÍO PATIA BAJO
 🔹 RÍO PATIA MEDIO
 🔹 RÍO PAUTO
 🔹 RÍO PESCADO
 🔹 RÍO PIENDAMO
 🔹 RÍO PORCE
 🔹 RÍO PRADO
 🔹 RÍO PUTUMAYO BAJO
 🔹 RÍO PUTUMAYO DIRECTOS (MI)
 🔹 RÍO PUTUMAYO MEDIO
 🔹 RÍO PÁEZ
 🔹 RÍO QUERARY
 🔹 RÍO QUINAMAYO Y OTROS DIRECTOS AL CAUCA
 🔹 RÍO QUITO
 🔹 RÍO RANCHERÍA
 🔹 RÍO RISARALDA
 🔹 RÍO ROSARIO
 🔹 RÍO SAIJA
 🔹 RÍO SALAQUÍ  Y OTROS DIRECTOS BAJO ATRATO
 🔹 RÍO SAN JORGE
 🔹 RÍO SAN JUAN
 🔹 RÍO SAN JUAN (FRONTERA ECUADOR)
 🔹 RÍO SAN JUAN ALTO
 🔹 RÍO SAN JUAN DEL MICAY
 🔹 RÍO SAN JUAN MEDIO
 🔹 RÍO SAN_MIGUEL
 🔹 RÍO SECO Y OTROS DIRECTOS AL MAGDALENA
 🔹 RÍO SIPÍ
 🔹 RÍO SOCUAVO DEL NORTE Y RÍO SOCUAVO SUR
 🔹 RÍO SOGAMOSO
 🔹 RÍO SUAZA
 🔹 RÍO SUCIO
 🔹 RÍO SUMAPAZ
 🔹 RÍO SUÁREZ
 🔹 RÍO TAMANÁ Y OTROS DIRECTOS SAN JUAN
 🔹 RÍO TANELA Y OTROS DIRECTOS AL CARIBE
 🔹 RÍO TAPAJE
 🔹 RÍO TAPIAS
 🔹 RÍO TARAZA - RÍO MAN
 🔹 RÍO TARRA
 🔹 RÍO TELEMBÍ
 🔹 RÍO TETUÁN, RÍO ORTEGA
 🔹 RÍO TIMANÁ Y OTROS DIRECTOS AL MAGDALENA
 🔹 RÍO TIMBA
 🔹 RÍO TIMBIQUÍ
 🔹 RÍO TOLO Y OTROS DIRECTOS AL CARIBE
 🔹 RÍO TOTARE
 🔹 RÍO TUPARRO
 🔹 RÍO TÚA Y OTROS DIRECTOS AL META
 🔹 RÍO UPÍA
 🔹 RÍO VITA
 🔹 RÍO YAGUARÁ Y RÍO IQUIRA
 🔹 RÍO YUCAO
 🔹 RÍO ZULIA
 🔹 RÍOS AMAIME Y CERRITO
 🔹 RÍOS CAJAMBRE - MAYORQUÍN - RAPOSO
 🔹 RÍOS CALI
 🔹 RÍOS CALIMA Y  BAJO SAN JUAN
 🔹 RÍOS CHIMICUICA Y COROZAL
 🔹 RÍOS CLARO Y JAMUNDÍ
 🔹 RÍOS DIRECTOS AL MAGDALENA (MI)
 🔹 RÍOS DIRECTOS MAGDALENA (MD)
 🔹 RÍOS GUABAS,SABALETAS Y SONSO
 🔹 RÍOS GUADALAJARA Y SAN PEDRO
 🔹 RÍOS LILÍ, MELENDEZ Y CANAVERALEJO
 🔹 RÍOS TULUA Y MORALES
 🔹 RÏO CUCUANA
 🔹 SAN ANDRES
------------------------------------------------------------------------------------------

💡 TOTAL DE OPCIONES ENCONTRADAS: 249
📌 INSTRUCCIÓN: Copie textualmente uno de los nombres en mayúscula, páselo a la siguiente celda y ejecútela.

In [36]:
df_estaciones.head()

,Codigo,Nombre,Descripcion,Categoria,Tecnologia,Estado,Departamento,Municipio,Altitud,Longitud,...,Fecha_instalacion,Fecha_suspension,Area_Operativa,Corriente,Area_Hidrografica,Zona_Hidrografica,Subzona_Hidrografica,Entidad,Subred,Red
0,26115050,GRAMAS LAS [26115050],GRAMAS LAS EN LA CORRIENTE: CAUCA,Climatológica Ordinaria,Convencional,Suspendida,Valle Del Cauca,Roldanillo,940,-76.116667,...,1967-07-15 00:00:00.000,1983-08-15 00:00:00.000,Area Operativa 09 - Cauca-Valle-Caldas,NaN,Magdalena Cauca,Cauca,Rios Pescador - RUT - Chanco - Catarina y Caña...,INSTITUTO DE HIDROLOGÍA METEOROLOGÍA Y ESTUDIO...,NaN,NaN
5,28027040,SANTA TERESA [28027040],STA TERESA,Limnimétrica,Convencional,Activa,Cesar,Agustín Codazzi,100,-73.256223,...,1962-11-15 00:00:00.000,NaN,Area Operativa 05 - Magdalena-Cesar-Guajira-Sa...,SICARARE,Magdalena Cauca,Cesar,Medio Cesar,INSTITUTO DE HIDROLOGÍA METEOROLOGÍA Y ESTUDIO...,NaN,NaN
6,26105150,SAN MARCOS [26105150],SAN MARCOS,Climatológica Ordinaria,Convencional,Activa,Valle Del Cauca,Bugalagrande,1011,-76.033056,...,1971-09-15 00:00:00.000,NaN,Area Operativa 09 - Cauca-Valle-Caldas,NaN,Magdalena Cauca,Cauca,Río Paila,INSTITUTO DE HIDROLOGÍA METEOROLOGÍA Y ESTUDIO...,Valle geografico Rio Cauca,Red de Agrometeorología
8,26185030,JERICO - AUT [26185030],DESLIZAMIENTO,Climatológica Principal,Automática con Telemetría,Suspendida,Antioquia,Jericó,2313,-75.789528,...,2004-11-28 00:00:00.000,2016-01-06 00:00:00.000,Area Operativa 01 - Antioquia-Chocó,NaN,Magdalena Cauca,Cauca,Río Frío y Otros Directos al Cauca,INSTITUTO DE HIDROLOGÍA METEOROLOGÍA Y ESTUDIO...,NaN,NaN
11,1506700110,POZO TIGRE [1506700110],Parte media del ay.bruno el la region del tigr...,Limnimétrica,Convencional,En Mantenimiento,La Guajira,Maicao,153,-72.499875,...,2018-04-21 00:00:00.000,NaN,Area Operativa 05 - Magdalena-Cesar-Guajira-Sa...,AY BRUNO,Caribe,Caribe - Guajira,Río Ranchería,INSTITUTO DE HIDROLOGÍA METEOROLOGÍA Y ESTUDIO...,NaN,NaN

## PASO 5C: Aplicación del Filtro Geográfico Definitivo

En `"valor_geografico_seleccionado"`, escriba textualmente el valor válido del filtro geográfico seleccionado a partir del listado generado en el anterior paso para aislar el subconjunto inicial de estaciones meteorológicas y/o hidrológicas.

In [37]:
# ==============================================================================
# PASO 5C: FILTRADO Y CONSOLIDACIÓN DEL ÁREA DE ESTUDIO GEOGRÁFICA
# ==============================================================================

# ==============================================================================
# MODIFIQUE AQUÍ: Pegue el valor real de la lista del paso anterior
# (El sistema es case-insensitive)
# ==============================================================================
valor_geografico_seleccionado = "RÍO SUMAPAZ"
# ==============================================================================

if 'CRITERIO_GEOGRAFICO_ACTIVO' in locals():
    # 1. Normalización del valor ingresado por el usuario
    valor_busqueda = valor_geografico_seleccionado.strip().upper()

    # 2. Aplicación del filtro sobre el catálogo analizado
    df_estaciones['tmp_geo_clean'] = df_estaciones[CRITERIO_GEOGRAFICO_ACTIVO].astype(str).str.strip().str.upper()
    df_estaciones_geo = df_estaciones[df_estaciones['tmp_geo_clean'] == valor_busqueda].copy()

    # Eliminamos la columna de control interno
    df_estaciones = df_estaciones.drop(columns=['tmp_geo_clean'])

    # 3. Despliegue y almacenamiento en memoria del subconjunto geográfico
    if not df_estaciones_geo.empty:
        total_estaciones_zona = len(df_estaciones_geo['Codigo'].unique())
        print(f"✅ FILTRO GEOGRÁFICO DE PRE-SELECCIÓN EJECUTADO CON ÉXITO")
        print("-" * 100)
        print(f"📍 Dimensión Geográfica: {CRITERIO_GEOGRAFICO_ACTIVO} ➡️ Valor Activo: '{valor_busqueda}'")
        print(f"📡 Cantidad de estaciones encontradas en esta zona: {total_estaciones_zona}")
        print("-" * 100)
        print("\n🚀 Subconjunto geográfico guardado en memoria de forma exitosa.")
        print("Proceda a la siguiente sección para aplicar los refinamientos técnicos de infraestructura.")
    else:
        print(f"❌ ERROR: El valor '{valor_geografico_seleccionado}' no arrojó resultados para la columna '{CRITERIO_GEOGRAFICO_ACTIVO}'.")
        print("Asegúrese de copiar exactamente un elemento del listado impreso en el Paso 5B.")
else:
    print("❌ ERROR DE SECUENCIA: Ejecute primero las celdas de los pasos 5A y 5B.")

✅ FILTRO GEOGRÁFICO DE PRE-SELECCIÓN EJECUTADO CON ÉXITO
----------------------------------------------------------------------------------------------------
📍 Dimensión Geográfica: Subzona_Hidrografica ➡️ Valor Activo: 'RÍO SUMAPAZ'
📡 Cantidad de estaciones encontradas en esta zona: 36
----------------------------------------------------------------------------------------------------

🚀 Subconjunto geográfico guardado en memoria de forma exitosa.
Proceda a la siguiente sección para aplicar los refinamientos técnicos de infraestructura.

## PASO 6: Refinamiento por Características Técnicas de la Estación

Una vez delimitada la zona geográfica de interés, es fundamental filtrar las estaciones según sus especificaciones técnicas de infraestructura. Por ejemplo, si está analizando caudales o niveles, le interesará concentrarse únicamente en estaciones de categoría *Limnigráfica* o *Limnimétrica* que se encuentren operativas (*Activas*).

En esta celda, usted cruzará tres dimensiones técnicas fundamentales empleando las opciones oficiales del repositorio del IDEAM:

1. **`Clase`:** Clase de estación (Ej: `"Hidrológica"`, `"Meteorológica"`)
2. **`Categoria`:** Categoría de estación (Ej: `"Limnigráfica"`, `"Limnimétrica"`, `"Pluviométrica"`, `"Climatológica Principal"`).
3. **`Estado`:** Condición operativa actual (`"Activa"`, `"En Mantenimiento"`, `"Suspendida"`).
4. **`Tecnologia`:** Tipo de tecnología (`"Convencional"`, `"Automática con Telemetría"`, `"Automática sin Telemetría"`).

---
**Instrucciones:** Escriba textualmente las variables de configuración con los atributos técnicos que requiera su consulta. Si no desea restringir alguna de las dimensiones, escriba simplemente `"TODOS"` en mayúsculas sostenidas.

In [38]:
# ==============================================================================
# PASO 6: REFINAMIENTO TÉCNICO DE INFRAESTRUCTURA (FILTRO DE CONTROL DE TOKENS)
# ==============================================================================

# ==============================================================================
# CONFIGURACIÓN DE ATRIBUTOS TÉCNICOS POR EL USUARIO
# ==============================================================================

# Opciones: "Limnigráfica", "Limnimétrica", "Pluviométrica", "Climatológica Principal", "TODOS"
filtro_categoria  = "Limnimétrica"

# Opciones: "Activa", "En Mantenimiento", "Suspendida", "TODOS"
filtro_estado     = "Activa"

# Opciones sugeridas: "Automática", "Convencional", "TODOS"
# (Si elige 'Automática', incluirá también las estaciones híbridas 'Automática + Convencional')
filtro_tecnologia = "Convencional"

# ==============================================================================

# --- Función auxiliar para remover tildes y caracteres especiales (No modificar) ---
def remover_tildes(texto):
    if not isinstance(texto, str):
        return str(texto)
    remplazos = (("Á", "A"), ("É", "E"), ("Í", "I"), ("Ó", "O"), ("Ú", "U"))
    t = texto.upper().strip()
    for original, reemplazo in remplazos:
        t = t.replace(original, reemplazo)
    return t

# --- Lógica de Filtrado Secuencial Cruzado (No modificar) ---

if 'df_estaciones_geo' in locals():
    # Partimos del subconjunto geográfico consolidado en el Paso 5C
    df_refinado = df_estaciones_geo.copy()

    # ---- 1. Filtrado por Categoría ----
    cat_usuario = remover_tildes(filtro_categoria)
    if cat_usuario != "TODOS":
        df_refinado['tmp_cat'] = df_refinado['Categoria'].apply(remover_tildes)
        df_refinado = df_refinado[df_refinado['tmp_cat'] == cat_usuario]
        df_refinado = df_refinado.drop(columns=['tmp_cat'])

    # ---- 2. Filtrado por Estado Operativo ----
    est_usuario = remover_tildes(filtro_estado)
    if est_usuario != "TODOS":
        df_refinado['tmp_est'] = df_refinado['Estado'].apply(remover_tildes)
        df_refinado = df_refinado[df_refinado['tmp_est'] == est_usuario]
        df_refinado = df_refinado.drop(columns=['tmp_est'])

    # ---- 3. Filtrado Inteligente por Tecnología (Resolución de Híbridos) ----
    tec_usuario = remover_tildes(filtro_tecnologia)
    if tec_usuario != "TODOS":
        df_refinado['tmp_tec'] = df_refinado['Tecnologia'].apply(remover_tildes)

        # Estrategia de Tokenización: Extraemos la raíz de la palabra seleccionada por el usuario
        # Si el usuario digita "Automática con Telemetría" o simplemente "Automática", el token principal será "AUTOMATICA"
        if "AUTOMATICA" in tec_usuario:
            token_busqueda = "AUTOMATICA"
        elif "CONVENCIONAL" in tec_usuario:
            token_busqueda = "CONVENCIONAL"
        else:
            token_busqueda = tec_usuario # Resguardo por si digita otro texto

        # El filtro busca el token dentro de la celda.
        # Así, un registro como "AUTOMÁTICA CON TELEMETRÍA, CONVENCIONAL" pasa la prueba si se busca "Automática" O "Convencional"
        df_refinado = df_refinado[df_refinado['tmp_tec'].str.contains(token_busqueda, na=False)]
        df_refinado = df_refinado.drop(columns=['tmp_tec'])

    # ---- 4. Despliegue de Resultados Definitivos ----
    if not df_refinado.empty:
        # Extraemos y blindamos la lista de códigos de estaciones final para el cruce de observaciones
        LISTA_ESTACIONES_TARGET = df_refinado['Codigo'].unique().tolist()

        print(f"✅ REFINAMIENTO TÉCNICO COMPLETADO CON ÉXITO (MÉTODO TOKENIZADO)")
        print("-" * 115)
        print(f"📊 Criterios Activos: Categoría = '{filtro_categoria.upper()}' | Estado = '{filtro_estado.upper()}' | Criterio Tecnología = '{filtro_tecnologia.upper()}'")
        print(f"🎯 Grupo de Control: Se han consolidado {len(LISTA_ESTACIONES_TARGET)} estaciones objetivo para la consulta histórica.")
        print("-" * 115)

        # Renderizado de la tabla final resumen en mayúsculas sostenidas para presentación
        columnas_resumen = ['Codigo', 'Nombre', 'Categoria', 'Tecnologia', 'Estado', 'Municipio', 'Corriente']
        df_vista_final = df_refinado[columnas_resumen].copy()
        for col in df_vista_final.columns:
            df_vista_final[col] = df_vista_final[col].astype(str).str.upper()

        print("\n📋 INVENTARIO DEFINITIVO DE ESTACIONES SELECCIONADAS:")
        print(df_vista_final.to_string(index=False))
    else:
        print("❌ No se encontraron estaciones en esta zona que cumplan simultáneamente con las características técnicas seleccionadas.")
        print("💡 Sugerencia: Flexibilice sus criterios (por ejemplo, cambie el filtro de Tecnología o Estado a 'TODOS') y vuelva a ejecutar.")
else:
    print("❌ ERROR DE SECUENCIA: No se detecta el subconjunto geográfico preliminar en memoria.")
    print("Por favor, ejecute primero la celda del Paso 5C.")

✅ REFINAMIENTO TÉCNICO COMPLETADO CON ÉXITO (MÉTODO TOKENIZADO)
-------------------------------------------------------------------------------------------------------------------
📊 Criterios Activos: Categoría = 'LIMNIMÉTRICA' | Estado = 'ACTIVA' | Criterio Tecnología = 'CONVENCIONAL'
🎯 Grupo de Control: Se han consolidado 3 estaciones objetivo para la consulta histórica.
-------------------------------------------------------------------------------------------------------------------

📋 INVENTARIO DEFINITIVO DE ESTACIONES SELECCIONADAS:
    Codigo                  Nombre    Categoria   Tecnologia Estado Municipio Corriente
2119700147 SAN MIGUEL [2119700147] LIMNIMÉTRICA CONVENCIONAL ACTIVA  RICAURTE   SUMAPAZ
  21197150   EL LIMONAR [21197150] LIMNIMÉTRICA CONVENCIONAL ACTIVA    MELGAR   SUMAPAZ
  21197110     SILVANIA [21197110] LIMNIMÉTRICA CONVENCIONAL ACTIVA  SILVANIA     SUBIA

## PASO 7: Definición del Rango Temporal de Consulta (Filtro Desde / Hasta)

Las observaciones históricas de las variables hidrológicas representan el volumen de datos más masivo dentro del repositorio **S3 (Simple Storage Service)**. Para optimizar los tiempos de descarga y el uso de memoria, es una buena práctica delimitar la ventana de tiempo que desea analizar.

Usted puede configurar este filtro de dos maneras:
1. **Rango Acotado (Recomendado para actualizaciones):** Defina fechas específicas de inicio y fin (Formato: `AAAA-MM-DD`) para traer únicamente los registros de un período particular.
2. **Histórico Total (Primera ejecución):** Puede dejar las fechas abiertas (o un rango muy amplio como `1900-01-01` hasta la fecha actual) para extraer toda la serie temporal disponible para el grupo de estaciones seleccionado.

---
**Instrucciones:** 1. Modifique la variable `fecha_desde` con la fecha inicial de la consulta.
2. Modifique la variable `fecha_hasta` con la fecha final de la consulta.
3. El sistema validará automáticamente que el formato sea correcto (`AAAA-MM-DD`) y que la fecha inicial sea menor o igual a la final antes de dar paso a la extracción física de las observaciones.

In [39]:
# ==============================================================================
# PASO 7: CONFIGURACIÓN Y VALIDACIÓN DEL RANGO DE FECHAS DE ESTUDIO
# ==============================================================================
import datetime

# ==============================================================================
# MODIFIQUE AQUÍ: Defina la ventana de tiempo para la extracción de observaciones
# Formato requerido: "AAAA-MM-DD" (Año-Mes-Día)
# ==============================================================================
fecha_desde = "2010-01-01"  # Modifique por la fecha inicial de su análisis
fecha_hasta = "2025-01-01"  # Modifique por la fecha final (o deje la fecha actual)
# ==============================================================================

# --- Lógica Institucional de Validación de Tiempos (No modificar) ---

def validar_formato_fecha(cadena_fecha):
    """Valida y convierte una cadena de texto a un objeto datetime.date"""
    try:
        return datetime.datetime.strptime(cadena_fecha.strip(), "%Y-%m-%d").date()
    except ValueError:
        return None

# Validamos que existan estaciones seleccionadas en el paso anterior
if 'LISTA_ESTACIONES_TARGET' in locals() and len(LISTA_ESTACIONES_TARGET) > 0:

    # Parseo y validación de las estructuras de fecha ingresadas por el usuario
    f_inicio = validar_formato_fecha(fecha_desde)
    f_final  = validar_formato_fecha(fecha_hasta)

    if f_inicio and f_final:
        # Validación de consistencia cronológica
        if f_inicio <= f_final:

            # Fijación de variables globales de control temporal en memoria del entorno
            FECHA_FILTRO_INICIO = f_inicio.strftime("%Y-%m-%d")
            FECHA_FILTRO_FINAL  = f_final.strftime("%Y-%m-%d")

            print(f"✅ RANGO TEMPORAL CONFIGURADO Y VALIDADO CON ÉXITO")
            print("-" * 80)
            print(f"📅 Fecha Inicial Activa: {FECHA_FILTRO_INICIO}")
            print(f"📅 Fecha Final Activa:   {FECHA_FILTRO_FINAL}")
            print(f"📡 Estaciones Objetivo en Memoria: {len(LISTA_ESTACIONES_TARGET)} estaciones.")
            if 'ETIQUETA_ESTUDIO' in locals():
                print(f"🏷️ Variable / Etiqueta Técnica Activa: '{ETIQUETA_ESTUDIO}'")
            print("-" * 80)
            print("\n🚀 El entorno de control está completamente blindado y listo.")
            print("Proceda a la siguiente celda para ejecutar la consulta masiva y la extracción física de datos.")

        else:
            print("❌ ERROR CRONOLÓGICO: La 'fecha_desde' no puede ser posterior a la 'fecha_hasta'.")
            print(f"Revisar: {fecha_desde} > {fecha_hasta}. Corrija los valores y vuelva a ejecutar.")
    else:
        print("❌ ERROR DE FORMATO: Una o ambas fechas no cumplen con la estructura estándar requerida.")
        print(f"Asegúrese de emplear estrictamente el formato 'AAAA-MM-DD' con guiones.")
        print(f"Valores ingresados actualmente ➡️ Desde: '{fecha_desde}' | Hasta: '{fecha_hasta}'")
else:
    print("❌ ERROR DE SECUENCIA: No se detecta la lista de estaciones objetivo en memoria.")
    print("Por favor, asegúrese de haber completado y ejecutado con éxito el Paso 6 antes de fijar las fechas.")

✅ RANGO TEMPORAL CONFIGURADO Y VALIDADO CON ÉXITO
--------------------------------------------------------------------------------
📅 Fecha Inicial Activa: 2010-01-01
📅 Fecha Final Activa:   2025-01-01
📡 Estaciones Objetivo en Memoria: 3 estaciones.
🏷️ Variable / Etiqueta Técnica Activa: 'Q_MEDIA_A'
--------------------------------------------------------------------------------

🚀 El entorno de control está completamente blindado y listo.
Proceda a la siguiente celda para ejecutar la consulta masiva y la extracción física de datos.

## PASO 7B: Configuración de la Ruta Local de Descarga y Autonomía de Datos

Para que las series de tiempo no se pierdan al cerrar esta sesión, el sistema exportará y guardará los datos de forma permanente en el disco duro de su computador.

Por cada estación que contenga registros dentro del rango de fechas definido, se generará de manera automática un archivo plano independiente utilizando la estructura de nomenclatura estándar: **`LABEL-ESTACION.csv`** (por ejemplo: `NIVEL_H-0026147140.csv`).

---
### 💡 Ventaja Hidro-Informática: Sincronización sin Trámites
Este diseño modular le otorga total autonomía técnica:
* **Cero Trámites:** Ya no requiere radicar solicitudes impresas ni peticiones tipo **PQR** ante la oficina de atención al ciudadano del IDEAM para acceder a la información histórica.
* **Actualización Incremental:** En el futuro, usted podrá abrir este mismo Notebook, ajustar la variable `fecha_desde` en el Paso 7 para apuntar a los últimos días del mes, volver a ejecutar el script, y sus archivos locales se actualizarán de forma inmediata con los datos más recientes depositados en el servidor de almacenamiento. Simple, directo y sin intermediarios.

---
**Instrucciones:** Modifique la variable `ruta_local_pc` escribiendo la ruta de la carpeta de su computadora donde desea que se almacenen los archivos CSV resultantes. Use barras inclinadas hacia adelante (`/`) para separar los directorios.

In [40]:
# ==============================================================================
# PASO 7B: DEFINICIÓN Y VERIFICACIÓN DE LA CARPETA LOCAL DE DESTINO
# ==============================================================================
import os

# ==============================================================================
# MODIFIQUE AQUÍ: Indique la ruta absoluta de la carpeta en su computador
# Ejemplos: "C:/Usuarios/TuNombre/Documentos/Datos_IDEAM"  (Windows)
#           "/Users/TuNombre/Documents/Datos_IDEAM"       (Mac/Linux)
# ==============================================================================
ruta_local_pc = "ourdata"
# ==============================================================================

# --- Lógica de Control de Directorios (No modificar) ---

# Limpieza y estandarización de la ruta de texto
RUTA_DESTINO_LOCAL = ruta_local_pc.strip().replace("\\", "/")

try:
    # Si la carpeta especificada por el usuario no existe, la creamos automáticamente
    if not os.path.exists(RUTA_DESTINO_LOCAL):
        os.makedirs(RUTA_DESTINO_LOCAL)
        print(f"📁 CARPETA CREADA: Se ha generado el directorio nuevo en su disco duro.")
    else:
        print(f"📁 CARPETA DETECTADA: El directorio especificado ya existe en el sistema.")

    # Validamos permisos de escritura intentando crear y borrar un archivo testigo de control
    archivo_testigo = os.path.join(RUTA_DESTINO_LOCAL, ".testigo_permisos").replace("\\", "/")
    with open(archivo_testigo, 'w') as f:
        f.write('OK')
    os.remove(archivo_testigo)

    print(f"✅ CARPETA LOCAL VALIDADA CON ÉXITO")
    print("-" * 85)
    print(f"📍 Directorio Activo de Descarga: '{RUTA_DESTINO_LOCAL}'")
    print("-" * 85)
    print("\n🚀 Ruta blindada. Proceda al Paso 8 para iniciar la descarga masiva directa a su PC.")

except Exception as e:
    print("🔴 ERROR CRÍTICO: No se puede acceder o escribir en la ruta local especificada.")
    print(f"❌ Detalle del sistema: {e}")
    print("\n💡 Sugerencia: Asegúrese de tener permisos de administrador en esa carpeta o intente")
    print("creando una carpeta directa en el disco C (ej: 'C:/Datos_IDEAM_Procesados').")

📁 CARPETA DETECTADA: El directorio especificado ya existe en el sistema.
✅ CARPETA LOCAL VALIDADA CON ÉXITO
-------------------------------------------------------------------------------------
📍 Directorio Activo de Descarga: 'ourdata'
-------------------------------------------------------------------------------------

🚀 Ruta blindada. Proceda al Paso 8 para iniciar la descarga masiva directa a su PC.

In [41]:
# ==============================================================================
# CELDA DE DIAGNÓSTICO: CHEQUEO DE VARIABLES REQUERIDAS PARA EL PASO 8
# ==============================================================================
variables_criticas = {
    'ETIQUETA_ESTUDIO': 'Paso 4 (Selección de Variable)',
    'LISTA_ESTACIONES_TARGET': 'Paso 6 (Refinamiento Técnico)',
    'FECHA_FILTRO_INICIO': 'Paso 7 (Rango de Fechas)',
    'FECHA_FILTRO_FINAL': 'Paso 7 (Rango de Fechas)',
    'RUTA_DESTINO_LOCAL': 'Paso 7B (Ruta Local de la PC)'
}

print("📋 ESTADO DE LAS VARIABLES DE CONTROL EN MEMORIA:")
print("-" * 75)
todas_ok = True

for var, paso in variables_criticas.items():
    if var in locals():
        # Evaluamos el contenido para dar un reporte detallado
        contenido = locals()[var]
        if isinstance(contenido, list):
            detalle = f"Lista con {len(contenido)} estaciones"
        else:
            detalle = f"'{contenido}'"
        print(f"🟢 {var:<25} ➡️ [OK] Creada en el {paso}. Valor: {detalle}")
    else:
        print(f"❌ {var:<25} ➡️ [FALTA] No detectada en memoria. Corresponde al {paso}.")
        todas_ok = False

print("-" * 75)
if todas_ok:
    print("🎯 ¡TODO PERFECTO! Las 5 variables están listas. Vuelva a lanzar la celda del Paso 8.")
else:
    print("💡 SOLUCIÓN: Vaya a los pasos marcados con [FALTA], ejecute esas celdas y luego regrese aquí.")

📋 ESTADO DE LAS VARIABLES DE CONTROL EN MEMORIA:
---------------------------------------------------------------------------
🟢 ETIQUETA_ESTUDIO          ➡️ [OK] Creada en el Paso 4 (Selección de Variable). Valor: 'Q_MEDIA_A'
🟢 LISTA_ESTACIONES_TARGET   ➡️ [OK] Creada en el Paso 6 (Refinamiento Técnico). Valor: Lista con 3 estaciones
🟢 FECHA_FILTRO_INICIO       ➡️ [OK] Creada en el Paso 7 (Rango de Fechas). Valor: '2010-01-01'
🟢 FECHA_FILTRO_FINAL        ➡️ [OK] Creada en el Paso 7 (Rango de Fechas). Valor: '2025-01-01'
🟢 RUTA_DESTINO_LOCAL        ➡️ [OK] Creada en el Paso 7B (Ruta Local de la PC). Valor: 'ourdata'
---------------------------------------------------------------------------
🎯 ¡TODO PERFECTO! Las 5 variables están listas. Vuelva a lanzar la celda del Paso 8.

## PASO 8A: Extracción y Consolidación Local (Entorno Jupyter)

A diferencia de los pasos anteriores donde hemos ejecutado procesos en la nube, este bloque está diseñado para integrarse directamente con su entorno de desarrollo local.

---
### ⚠️ Requisito Técnico para la Ejecución Local
Para que el script pueda gestionar la descarga y escritura de sus archivos en su disco duro de manera autónoma, es indispensable que cuente con **Jupyter Notebook** (o JupyterLab) instalado en su computadora junto con una distribución de **Python**.

**¿Por qué este paso es multiplataforma?**
Hemos implementado una arquitectura basada en el módulo `pathlib`, lo que significa que el código es **100% independiente del Sistema Operativo**:
* **Si usa Windows:** El script identificará automáticamente sus rutas (ej: `C:\Usuarios\...`).
* **Si usa macOS o Linux:** El script gestionará sus directorios nativos sin errores.

**¿Qué realiza este paso?**
1. **Conexión Directa:** Establece un puente entre su máquina local y el S3 del IDEAM.
2. **Escritura Nativa:** Crea, ordena y guarda cada archivo `.csv` en la carpeta que usted haya definido en su equipo.
3. **Autonomía:** Al correr este proceso localmente, usted evita tiempos de latencia de red en la nube y mantiene un respaldo físico inmediato de sus series de tiempo.

---
**Instrucciones:** Asegúrese de haber instalado las librerías necesarias (`pip install pandas pyarrow s3fs`). Una vez verificado su entorno local, ejecute la celda a continuación. El sistema le notificará el progreso de la escritura en tiempo real.

In [42]:
# ==============================================================================
# PASO 8A: EXTRACTOR USANDO JUPYTER LOCAL PARA MULTIPLES SISTEMAS OPERATIVOS
# ==============================================================================
import os
from pathlib import Path
import pandas as pd

var_etiqueta   = globals().get('ETIQUETA_ESTUDIO', locals().get('ETIQUETA_ESTUDIO'))
var_estaciones = globals().get('LISTA_ESTACIONES_TARGET', locals().get('LISTA_ESTACIONES_TARGET'))
var_f_inicio   = globals().get('FECHA_FILTRO_INICIO', locals().get('FECHA_FILTRO_INICIO'))
var_f_final    = globals().get('FECHA_FILTRO_FINAL', locals().get('FECHA_FILTRO_FINAL'))
var_ruta_pc    = globals().get('RUTA_DESTINO_LOCAL', locals().get('RUTA_DESTINO_LOCAL'))
opciones_env   = globals().get('opciones_almacenamiento')

ts_inicio = pd.to_datetime(var_f_inicio)
ts_final  = pd.to_datetime(var_f_final)

# --- RESOLUCIÓN ABSOLUTA DE RUTA EN MAC ---
# pathlib.Path resuelve el directorio real expandiendo cualquier restricción del sistema
directorio_destino = Path(var_ruta_pc.strip()).resolve()
directorio_destino.mkdir(parents=True, exist_ok=True)

print("🚀 INICIANDO EXTRACCIÓN CON ESCRITURA FÍSICA DIRECTA EN DISCO...")
print("-" * 95)
print(f"📁 Carpeta Real Verificada: {directorio_destino}")
print("-" * 95)

estaciones_exportadas = 0
total_filas_guardadas = 0

for cod_estacion in var_estaciones:
    id_estacion = str(cod_estacion).strip().zfill(10)
    ruta_particion = f"s3://s3-estacionesideam/observaciones/historicos/parquet/label={var_etiqueta}/id_estacion={id_estacion}"

    try:
        df_particion = pd.read_parquet(ruta_particion, storage_options=opciones_env)

        if df_particion.empty:
            continue

        df_particion['label'] = var_etiqueta
        df_particion['id_estacion'] = id_estacion
        df_particion['fecha'] = pd.to_datetime(df_particion['fecha'])

        mascara_fechas = (df_particion['fecha'] >= ts_inicio) & (df_particion['fecha'] <= ts_final)
        df_estacion_filtrado = df_particion[mascara_fechas].copy()

        if not df_estacion_filtrado.empty:
            columnas_ordenadas = ['label', 'id_estacion', 'fecha', 'valor', 'nivel_aprobacion']
            df_estacion_filtrado = df_estacion_filtrado[columnas_ordenadas]
            df_estacion_filtrado = df_estacion_filtrado.sort_values(by='fecha').reset_index(drop=True)

            # Formateo visual strings
            df_estacion_filtrado['label'] = df_estacion_filtrado['label'].astype(str).str.upper()
            df_estacion_filtrado['nivel_aprobacion'] = df_estacion_filtrado['nivel_aprobacion'].astype(str).str.upper()

            # --- CONSTRUCCIÓN DE RUTA NATIVA MAC ---
            nombre_archivo = f"{var_etiqueta.upper()}-{id_estacion}.csv"
            ruta_archivo_fisico = directorio_destino / nombre_archivo

            # Forzamos la escritura con flush de sistema
            df_estacion_filtrado.to_csv(ruta_archivo_fisico, index=False, encoding='utf-8')

            estaciones_exportadas += 1
            total_filas_guardadas += len(df_estacion_filtrado)
            print(f"✅ ARCHIVO ESCRITO EN DISCO ➡️ {nombre_archivo} ({len(df_estacion_filtrado)} filas)")

    except Exception:
        continue

print("-" * 95)
print(f"🏁 PROCESO TERMINADO. Archivos físicos reales creados: {estaciones_exportadas}")
print(f"📊 Total registros transferidos: {total_filas_guardadas}")

🚀 INICIANDO EXTRACCIÓN CON ESCRITURA FÍSICA DIRECTA EN DISCO...
-----------------------------------------------------------------------------------------------
📁 Carpeta Real Verificada: /home/santy/Projects/GitProjects/Geopositioning-and-Navigation/ourdata
-----------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------
🏁 PROCESO TERMINADO. Archivos físicos reales creados: 0
📊 Total registros transferidos: 0

## PASO 8B: Extracción Masiva en la Nube y Descarga al Navegador

Este bloque está optimizado específicamente para ejecutarse en el entorno de **Google Colab**. Dado que Colab opera en servidores remotos (en la nube), los archivos generados no se guardan directamente en su disco duro local, sino en una memoria temporal del servidor.

---
### 💡 ¿Cómo funciona la descarga desde la nube?
Para entregarle los datos en su computadora, el script realiza los siguientes pasos de manera automatizada:
1. **Procesamiento en Servidor:** El servidor de Google Colab consulta, filtra y consolida las series de tiempo desde el S3 del IDEAM a gran velocidad.
2. **Generación de Archivos:** Crea los archivos `.csv` listos para su análisis.
3. **Puente de Descarga (Navegador):** Utilizamos la librería nativa `google.colab.files` que interactúa con su navegador web. Esto disparará una descarga automática de cada archivo directamente a su carpeta de **Descargas** (Downloads) en su computadora local.

---
### 📌 Notas Importantes para esta Ejecución:
* **Ventana Emergente:** Es posible que su navegador le pida permiso para realizar "múltiples descargas automáticas". Por favor, seleccione **"Permitir"** en la parte superior derecha de su navegador para que el proceso no se interrumpa.
* **Sin requerimientos adicionales:** No necesita instalar nada localmente. Todo el cómputo pesado lo realiza la infraestructura de Google.
* **Actualización:** Usted podrá volver a este cuaderno en cualquier momento, cambiar las fechas o estaciones, y obtener los archivos más recientes con solo ejecutar este bloque.

---
**Instrucciones:** Ejecute la celda a continuación y mantenga la ventana del navegador abierta mientras los archivos se transfieren de forma segura a su PC.

In [43]:
"""
# ==============================================================================
# PASO 8B: EXTRACTOR MASIVO OPTIMIZADO PARA GOOGLE COLAB CON DESCARGA A PC
# ==============================================================================
import os
from pathlib import Path
import pandas as pd
from google.colab import files  # Librería nativa para interactuar con tu PC real

var_etiqueta   = globals().get('ETIQUETA_ESTUDIO', locals().get('ETIQUETA_ESTUDIO'))
var_estaciones = globals().get('LISTA_ESTACIONES_TARGET', locals().get('LISTA_ESTACIONES_TARGET'))
var_f_inicio   = globals().get('FECHA_FILTRO_INICIO', locals().get('FECHA_FILTRO_INICIO'))
var_f_final    = globals().get('FECHA_FILTRO_FINAL', locals().get('FECHA_FILTRO_FINAL'))
opciones_env   = globals().get('opciones_almacenamiento')

ts_inicio = pd.to_datetime(var_f_inicio)
ts_final  = pd.to_datetime(var_f_final)

# En Colab, creamos una carpeta temporal dentro de la máquina virtual de Google
directorio_temporal_colab = Path("./datos_ideam_temporales")
directorio_temporal_colab.mkdir(parents=True, exist_ok=True)

print("🚀 INICIANDO EXTRACCIÓN EN LA NUBE DE COLAB...")
print("-" * 95)

estaciones_exportadas = 0

for cod_estacion in var_estaciones:
    id_estacion = str(cod_estacion).strip().zfill(10)
    ruta_particion = f"s3://s3-estacionesideam/observaciones/historicos/parquet/label={var_etiqueta}/id_estacion={id_estacion}"

    try:
        df_particion = pd.read_parquet(ruta_particion, storage_options=opciones_env)
        if df_particion.empty:
            continue

        df_particion['label'] = var_etiqueta
        df_particion['id_estacion'] = id_estacion
        df_particion['fecha'] = pd.to_datetime(df_particion['fecha'])

        mascara_fechas = (df_particion['fecha'] >= ts_inicio) & (df_particion['fecha'] <= ts_final)
        df_estacion_filtrado = df_particion[mascara_fechas].copy()

        if not df_estacion_filtrado.empty:
            columnas_ordenadas = ['label', 'id_estacion', 'fecha', 'valor', 'nivel_aprobacion']
            df_estacion_filtrado = df_estacion_filtrado[columnas_ordenadas]
            df_estacion_filtrado = df_estacion_filtrado.sort_values(by='fecha').reset_index(drop=True)

            # Formateo de strings
            df_estacion_filtrado['label'] = df_estacion_filtrado['label'].astype(str).str.upper()
            df_estacion_filtrado['nivel_aprobacion'] = df_estacion_filtrado['nivel_aprobacion'].astype(str).str.upper()

            # Guardamos el archivo temporalmente en el servidor de Google
            nombre_archivo = f"{var_etiqueta.upper()}-{id_estacion}.csv"
            ruta_temporal_archivo = directorio_temporal_colab / nombre_archivo
            df_estacion_filtrado.to_csv(ruta_temporal_archivo, index=False, encoding='utf-8')

            print(f"📦 Procesado en la nube ➡️ {nombre_archivo}")

            # --- EL TRUCO PARA TU MAC ---
            # Le ordenamos al navegador que descargue el archivo guardado en Google a tu PC real
            print(f"⬇️ Transfiriendo '{nombre_archivo}' a su computador local...")
            files.download(str(ruta_temporal_archivo))

            estaciones_exportadas += 1

    except Exception:
        continue

print("-" * 95)
print(f"🏁 PROCESO TERMINADO. Archivos enviados a tu carpeta de Descargas local: {estaciones_exportadas}")
"""

'\n# ==============================================================================\n# PASO 8B: EXTRACTOR MASIVO OPTIMIZADO PARA GOOGLE COLAB CON DESCARGA A PC\n# ==============================================================================\nimport os\nfrom pathlib import Path\nimport pandas as pd\nfrom google.colab import files  # Librería nativa para interactuar con tu PC real\n\nvar_etiqueta   = globals().get(\'ETIQUETA_ESTUDIO\', locals().get(\'ETIQUETA_ESTUDIO\'))\nvar_estaciones = globals().get(\'LISTA_ESTACIONES_TARGET\', locals().get(\'LISTA_ESTACIONES_TARGET\'))\nvar_f_inicio   = globals().get(\'FECHA_FILTRO_INICIO\', locals().get(\'FECHA_FILTRO_INICIO\'))\nvar_f_final    = globals().get(\'FECHA_FILTRO_FINAL\', locals().get(\'FECHA_FILTRO_FINAL\'))\nopciones_env   = globals().get(\'opciones_almacenamiento\')\n\nts_inicio = pd.to_datetime(var_f_inicio)\nts_final  = pd.to_datetime(var_f_final)\n\n# En Colab, creamos una carpeta temporal dentro de la máquina virtual de Google\ndirectorio_temporal_colab = Path("./datos_ideam_temporales")\ndirectorio_temporal_colab.mkdir(parents=True, exist_ok=True)\n\nprint("🚀 INICIANDO EXTRACCIÓN EN LA NUBE DE COLAB...")\nprint("-" * 95)\n\nestaciones_exportadas = 0\n\nfor cod_estacion in var_estaciones:\n    id_estacion = str(cod_estacion).strip().zfill(10)\n    ruta_particion = f"s3://s3-estacionesideam/observaciones/historicos/parquet/label={var_etiqueta}/id_estacion={id_estacion}"\n\n    try:\n        df_particion = pd.read_parquet(ruta_particion, storage_options=opciones_env)\n        if df_particion.empty:\n            continue\n\n        df_particion[\'label\'] = var_etiqueta\n        df_particion[\'id_estacion\'] = id_estacion\n        df_particion[\'fecha\'] = pd.to_datetime(df_particion[\'fecha\'])\n\n        mascara_fechas = (df_particion[\'fecha\'] >= ts_inicio) & (df_particion[\'fecha\'] <= ts_final)\n        df_estacion_filtrado = df_particion[mascara_fechas].copy()\n\n        if not df_estacion_filtrado.empty:\n            columnas_ordenadas = [\'label\', \'id_estacion\', \'fecha\', \'valor\', \'nivel_aprobacion\']\n            df_estacion_filtrado = df_estacion_filtrado[columnas_ordenadas]\n            df_estacion_filtrado = df_estacion_filtrado.sort_values(by=\'fecha\').reset_index(drop=True)\n\n            # Formateo de strings\n            df_estacion_filtrado[\'label\'] = df_estacion_filtrado[\'label\'].astype(str).str.upper()\n            df_estacion_filtrado[\'nivel_aprobacion\'] = df_estacion_filtrado[\'nivel_aprobacion\'].astype(str).str.upper()\n\n            # Guardamos el archivo temporalmente en el servidor de Google\n            nombre_archivo = f"{var_etiqueta.upper()}-{id_estacion}.csv"\n            ruta_temporal_archivo = directorio_temporal_colab / nombre_archivo\n            df_estacion_filtrado.to_csv(ruta_temporal_archivo, index=False, encoding=\'utf-8\')\n\n            print(f"📦 Procesado en la nube ➡️ {nombre_archivo}")\n\n            # --- EL TRUCO PARA TU MAC ---\n            # Le ordenamos al navegador que descargue el archivo guardado en Google a tu PC real\n            print(f"⬇️ Transfiriendo \'{nombre_archivo}\' a su computador local...")\n            files.download(str(ruta_temporal_archivo))\n\n            estaciones_exportadas += 1\n\n    except Exception:\n        continue\n\nprint("-" * 95)\nprint(f"🏁 PROCESO TERMINADO. Archivos enviados a tu carpeta de Descargas local: {estaciones_exportadas}")\n'

# El otro csv

In [46]:
ungrd = pd.read_csv("ourdata/Emergencias_UNGRD_V2_20260930.csv")
ungrd

,FECHA,DEPARTAMENTO,MUNICIPIO,EVENTO,CODIFICACIÓN SEGUN DIVIPOLA,COORDENADAS,FALLECIDOS,HERIDOS,DESAPARECIDOS,PERSONAS,...,VALOR - AGUA Y SANEAMIENTO BASICO,ACCIONES ESPECIFICAS - OBRAS DE EMERGENCIA - \nBANCO DE MAQUINARIA,VALOR - OBRAS DE EMERGENCIA - \nBANCO DE MAQUINARIA,DESCRIPCION - OTROS APOYOS,VALOR - OTROS APOYOS,No DECRETO DE CALAMIDAD PUBLICA,INICIO DECRETO DE CALAMIDAD PUBLICA,COMENTARIOS,CODIGO EMERGENCIA,VALOR - APOYO TOTAL DEL FNGRD
0,2025 Jan 01 12:00:00 AM,CESAR,BECERRIL,AVENIDA TORRENCIAL,"20,045",0,0,0,0,32,...,$ - 0,No Registra,$ - 0,No Registra,$ - 0,0,No Registra,"CDGRD CESAR INFORMA, MUNICIPIO: BECERRIL - ZON...",1,$ 0.00
1,2025 Jan 01 12:00:00 AM,CESAR,CHIRIGUANA,INCENDIO ESTRUCTURAL,"20,046",0,0,0,0,4,...,$ - 0,No Registra,$ - 0,No Registra,$ - 0,0,No Registra,"CDGRD CESAR INFORMA, MUNICIPIO: CHIRIGUANA - Z...",2,$ 0.00
2,2025 Jan 01 12:00:00 AM,CESAR,EL PASO,INCENDIO FORESTAL,"20,047",0,0,0,0,0,...,$ - 0,No Registra,$ - 0,No Registra,$ - 0,0,No Registra,"CDGRD CESAR INFORMA, MUNICIPIO: EL PASO - ZONA...",3,$ 0.00
3,2025 Jan 01 12:00:00 AM,CESAR,BECERRIL,VENDAVAL,"20,048",0,0,0,0,4,...,$ - 0,No Registra,$ - 0,No Registra,$ - 0,0,No Registra,CDGRD CESAR INFORMA: MUNICIPIO: BECERRIL - ZON...,4,$ 0.00
4,2025 Jan 01 12:00:00 AM,LA GUAJIRA,RIOHACHA,INCENDIO ESTRUCTURAL,"20,049",0,0,0,0,5,...,$ - 0,No Registra,$ - 0,No Registra,$ - 0,0,No Registra,"CDGRD L A GUAJIRA INFORMA, MEDIANTE REPORTE SE...",5,$ 0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13007,2025 May 14 12:00:00 AM,BOLIVAR,DEPARTAMENTO,INUNDACION,13,0,0,0,0,0,...,$ - 0,No Registra,$ - 0,No Registra,$ - 0,No. 999,2024-11-20T00:00:00.000,"Arenal, Morales, San Pablo, Simití","6,501","$ 1,082,663,071.00"
13008,2025 May 14 12:00:00 AM,BOLIVAR,DEPARTAMENTO,INUNDACION,13,0,0,0,0,0,...,$ - 0,No Registra,$ - 0,No Registra,$ - 0,No. 999,2024-11-20T00:00:00.000,"El Carmen De Bolívar, San Jacinto","6,502","$ 2,490,066,498.64"
13009,2025 Apr 28 12:00:00 AM,CHOCO,DEPARTAMENTO,INUNDACION,27,0,0,0,0,0,...,$ - 0,No Registra,$ - 0,No Registra,$ - 0,No. 0282,2024-11-10T00:00:00.000,"Alto Baudó, Bajo Baudó","6,503","$ 1,569,096,396.00"
13010,2025 Apr 25 12:00:00 AM,CHOCO,DEPARTAMENTO,INUNDACION,27,0,0,0,0,0,...,$ - 0,No Registra,$ - 0,No Registra,$ - 0,No. 0282,2024-11-10T00:00:00.000,"San José Del Palmar, Tadó","6,504","$ 1,499,737,960.00"
13011,2025 Apr 28 12:00:00 AM,CHOCO,DEPARTAMENTO,INUNDACION,27,0,0,0,0,0,...,$ - 0,No Registra,$ - 0,No Registra,$ - 0,No. 0282,2024-11-10T00:00:00.000,"Bagadó, El Carmen De Atrato, Lloró","6,505","$ 1,972,895,573.60"

In [ ]:
ungrd["EVENTO"].unique()

<StringArray>
[               'AVENIDA TORRENCIAL',              'INCENDIO ESTRUCTURAL',
                 'INCENDIO FORESTAL',                          'VENDAVAL',
                  'CRECIENTE SUBITA',                'MOVIMIENTO EN MASA',
    'ACCIDENTE TRANSPORTE TERRESTRE',                        'INUNDACION',
                           'EROSION',                     'CASO FORTUITO',
                         'INMERSION',        'ACCIDENTE TRANSPORTE AEREO',
                  'ACCIDENTE MINERO',               'ACTIVIDAD VOLCANICA',
                            'HELADA',                            'SEQUIA',
         'DESABASTECIMIENTO DE AGUA',                'ACCIDENTE MARITIMO',
                         'GRANIZADA',               'COLAPSO ESTRUCTURAL',
                'TORMENTA ELECTRICA',                         'EXPLOSION',
                   'EROSION COSTERA',                          'INCENDIO',
                              'FUGA',                             'SISMO',
                 'ACCIDENTE FLUVIAL',             'ACCIDENTE TECNOLOGICO',
 'ACCIDENTE DE TRANSPORTE TERRESTRE',                       'No Registra']
Length: 30, dtype: str

In [52]:
eventos_hidrologicos = [
    "AVENIDA TORRENCIAL",
    "CRECIENTE SUBITA",
    "INUNDACION",
    "MOVIMIENTO EN MASA",
    "EROSION",
    "SEQUIA",
    "DESABASTECIMIENTO DE AGUA",
    "ACCIDENTE FLUVIAL",
    "EROSION COSTERA",
]

In [54]:
ungrd[
    ungrd["EVENTO"].isin(eventos_hidrologicos)]

,FECHA,DEPARTAMENTO,MUNICIPIO,EVENTO,CODIFICACIÓN SEGUN DIVIPOLA,COORDENADAS,FALLECIDOS,HERIDOS,DESAPARECIDOS,PERSONAS,...,VALOR - AGUA Y SANEAMIENTO BASICO,ACCIONES ESPECIFICAS - OBRAS DE EMERGENCIA - \nBANCO DE MAQUINARIA,VALOR - OBRAS DE EMERGENCIA - \nBANCO DE MAQUINARIA,DESCRIPCION - OTROS APOYOS,VALOR - OTROS APOYOS,No DECRETO DE CALAMIDAD PUBLICA,INICIO DECRETO DE CALAMIDAD PUBLICA,COMENTARIOS,CODIGO EMERGENCIA,VALOR - APOYO TOTAL DEL FNGRD
0,2025 Jan 01 12:00:00 AM,CESAR,BECERRIL,AVENIDA TORRENCIAL,"20,045",0,0,0,0,32,...,$ - 0,No Registra,$ - 0,No Registra,$ - 0,0,No Registra,"CDGRD CESAR INFORMA, MUNICIPIO: BECERRIL - ZON...",1,$ 0.00
5,2025 Jan 01 12:00:00 AM,META,PUERTO LOPEZ,CRECIENTE SUBITA,"20,050",0,1,0,0,0,...,$ - 0,No Registra,$ - 0,No Registra,$ - 0,0,No Registra,"CDGRD META, INFORMA\nMUNICIPIO PUERTO LÓPEZ, V...",6,$ 0.00
6,2025 Jan 01 12:00:00 AM,NARIÑO,ARBOLEDA,MOVIMIENTO EN MASA,"20,051",0,0,0,0,0,...,$ - 0,No Registra,$ - 0,No Registra,$ - 0,0,No Registra,"CDGRD NARIÑO, INFORMA\nMUNICIPIO ARBOLEDA, VÍA...",7,$ 0.00
8,2025 Jan 01 12:00:00 AM,TOLIMA,RIOBLANCO,MOVIMIENTO EN MASA,"20,053",0,0,0,0,5,...,$ - 0,No Registra,$ - 0,No Registra,$ - 0,0,No Registra,"CDGRD TOLIMA INFORMA, MUNICIPIO: RÍO BLANCO - ...",9,$ 0.00
9,2025 Jan 01 12:00:00 AM,VALLE DEL CAUCA,CALI,CRECIENTE SUBITA,"20,054",0,1,0,0,0,...,$ - 0,No Registra,$ - 0,No Registra,$ - 0,0,No Registra,CDGRD VALLE DEL CAUCA INFORMA: MUNICIPIO: CALI...,10,$ 0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13007,2025 May 14 12:00:00 AM,BOLIVAR,DEPARTAMENTO,INUNDACION,13,0,0,0,0,0,...,$ - 0,No Registra,$ - 0,No Registra,$ - 0,No. 999,2024-11-20T00:00:00.000,"Arenal, Morales, San Pablo, Simití","6,501","$ 1,082,663,071.00"
13008,2025 May 14 12:00:00 AM,BOLIVAR,DEPARTAMENTO,INUNDACION,13,0,0,0,0,0,...,$ - 0,No Registra,$ - 0,No Registra,$ - 0,No. 999,2024-11-20T00:00:00.000,"El Carmen De Bolívar, San Jacinto","6,502","$ 2,490,066,498.64"
13009,2025 Apr 28 12:00:00 AM,CHOCO,DEPARTAMENTO,INUNDACION,27,0,0,0,0,0,...,$ - 0,No Registra,$ - 0,No Registra,$ - 0,No. 0282,2024-11-10T00:00:00.000,"Alto Baudó, Bajo Baudó","6,503","$ 1,569,096,396.00"
13010,2025 Apr 25 12:00:00 AM,CHOCO,DEPARTAMENTO,INUNDACION,27,0,0,0,0,0,...,$ - 0,No Registra,$ - 0,No Registra,$ - 0,No. 0282,2024-11-10T00:00:00.000,"San José Del Palmar, Tadó","6,504","$ 1,499,737,960.00"
13011,2025 Apr 28 12:00:00 AM,CHOCO,DEPARTAMENTO,INUNDACION,27,0,0,0,0,0,...,$ - 0,No Registra,$ - 0,No Registra,$ - 0,No. 0282,2024-11-10T00:00:00.000,"Bagadó, El Carmen De Atrato, Lloró","6,505","$ 1,972,895,573.60"